# Generated by Django 4.0.1 on 2023-05-31 13:00

from django.db import migrations
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', tasks.models.UserManager()),
            ],
        ),
    ]
