# Generated by Django 4.0.1 on 2023-05-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='send_next_report_at',
            new_name='send_report_at',
        ),
        migrations.AddField(
            model_name='user',
            name='last_sent_on',
            field=models.DateField(null=True),
        ),
    ]
